products:
  tenablesc-metrics:
    build:
      main-pkg: ./main
      version-var: github.com/palantir/tenablesc-metrics/version.version
      os-archs:
        - os: darwin
          arch: amd64
        - os: darwin
          arch: arm64
        - os: linux
          arch: amd64
        - os: linux
          arch: arm
        - os: windows
          arch: amd64
    dist:
      disters:
        os-arch-bin:
          type: os-arch-bin
          config: 
            os-archs:
              - os: darwin
                arch: amd64
              - os: darwin
                arch: arm64
              - os: linux
                arch: amd64
              - os: linux
                arch: arm
              - os: windows
                arch: amd64
    publish: {}
product-defaults:
  publish:
    group-id: com.palantir.tenablesc-metrics
